In [2]:
## 1
import numpy as np
from IPython.display import display

num16 = np.arange(1, 17)
num16.resize(4, 4)
display(num16)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
## 2
num1050 = np.arange(10, 51, 5)
num1050.resize(2,4)
display(num1050)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [28]:
## 3
num1100 = np.random.randint(1, 101, 9)
num1100.resize(3,3)
print(num1100)
print(num1100.max())
print(num1100.min())

[[44 23 13]
 [22 54 89]
 [12 33 85]]
89
12


In [58]:
## BONUS 4
num20 = np.random.randint(1, 21, 10)

print(num20)

print("5 first", num20[:5])
print("jump 2", num20[::2])
print("reverse", num20[::-1])

[20 19 14  8 17  6 16  5 17  3]
5 first [20 19 14  8 17]
jump 2 [20 14 17 16 17]
reverse [ 3 17  5 16  6 17  8 14 19 20]


In [80]:
## BONUS 5
num150 = np.random.randint(1, 51, (4,5))
print(num150)

print("second row", num150[1])
print("collum four", num150[:, 3])

[[47 11 13 46 16]
 [ 5 46 22 29  3]
 [37 44 44 40  5]
 [30 26 26 35 29]]
second row [ 5 46 22 29  3]
collum four [46 29 40 35]


In [118]:
## BONUS 6
num15 = np.random.randint(0, 101, 15)
print(num15)

print(f"index of {num15.max()} (max)", num15.argmax())
print(f"index of {num15.min()} (min)", num15.argmin())

[45 90 65 10 47 74 41 76 28  7 11  2 37 29 74]
index of 90 (max) 1
index of 2 (min) 11


In [134]:
## continue 6
np.save("num15.npy", num15)
print(np.load("num15.npy"))

filtered_num15div5 = num15[num15 % 5 == 0]
print("divisible by 5:", filtered_num15div5)

filterednum15b = num15[(10 < num15)| (num15 > 50)]
print("smaller than 10 OR bigger than 50:", filterednum15b)

[45 90 65 10 47 74 41 76 28  7 11  2 37 29 74]
divisible by 5: [45 90 65 10]
smaller than 10 OR bigger than 50: [45 90 65 47 74 41 76 28 11 37 29 74]


In [163]:
## BONUS / CHALLENGE
most_above_80_seed = None
max_nums_above_80 = 0


for seed in range(10, 101):
    np.random.seed(seed)
    nums = np.random.randint(1, 101, 15)
    nums_above_80 = np.sum(nums > 80)
    
    if nums_above_80 > max_nums_above_80:
        max_nums_above_80 = nums_above_80
        most_above_80_seed = seed

np.random.seed(most_above_80_seed)
numbers = np.random.randint(1, 101, 15)
count_above_80 = np.sum(numbers > 80)

print(f"heres the numbers: {numbers}")
print(f"the best seed was {most_above_80_seed}, it had {count_above_80} numbers above 80.")

heres the numbers: [86 35 41 97 25 86 84 98 95 95 76 28 70 21 79]
the best seed was 29, it had 7 numbers above 80.
