In [303]:
import numpy as np

#1
print(np.arange(1, 10))
## print(np.arange(1, 11))
print(np.arange(0.5, 5, 0.25))
## print(np.arange(0.5, 5.25, 0.25))

[1 2 3 4 5 6 7 8 9]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75]


In [305]:
#2
print(np.zeros(10))
print(np.zeros((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [307]:
#3
print(np.linspace(2, 12, 5))
print(np.linspace(3, 9, 4))

[ 2.   4.5  7.   9.5 12. ]
[3. 5. 7. 9.]


In [309]:
#4
#a
reshapable = np.random.rand(2,4)
print(reshapable)
#b
print(np.random.randint(10, 21, size=(3,3)))
#c
print(np.reshape(reshapable, (1,8))) # be careful to store the values so it would not randomize again

[[0.4671373  0.42192488 0.42414256 0.20400455]
 [0.87782193 0.33156152 0.37527025 0.88332608]]
[[13 18 17]
 [18 14 10]
 [12 19 13]]
[[0.4671373  0.42192488 0.42414256 0.20400455 0.87782193 0.33156152
  0.37527025 0.88332608]]


In [311]:
#5
# the random numbers will be predictable, we would get the same numbers again and again
# with seed, you can recycle your results, compare and share them.