In [300]:
import numpy as np

#1
print(np.arange(1, 10))
## print(np.arange(1, 11))
print(np.arange(0.5, 5, 0.25))
## print(np.arange(0.5, 5.25, 0.25))

#2
print(np.zeros(10))
print(np.zeros((3,4)))

#3
print(np.linspace(2, 12, 5))
print(np.linspace(3, 9, 4))

#4
#a
reshapable = np.random.rand(2,4)
print(reshapable)
#b
print(np.random.randint(10, 21, size=(3,3)))
#c
print(np.reshape(reshapable, (1,8))) # be careful to store the values so it would not randomize again

#5
# the random numbers will be predictable, we would get the same numbers again and again
# with seed, you can recycle your results, compare and share them.

[1 2 3 4 5 6 7 8 9]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 2.   4.5  7.   9.5 12. ]
[3. 5. 7. 9.]
[[0.81651538 0.21726874 0.54985772 0.89797646]
 [0.584744   0.30501947 0.93072645 0.25125526]]
[[10 17 16]
 [12 17 11]
 [13 13 12]]
[[0.81651538 0.21726874 0.54985772 0.89797646 0.584744   0.30501947
  0.93072645 0.25125526]]
