In [42]:
import numpy as np
from IPython.display import display

# 1
nums1 = np.arange(18, 54)
nums1.resize(6, 6)
display(nums1)
selected_num = nums1[3][2]
print(selected_num + 17) # No, its 55.

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

55


In [40]:
np.random.seed(42)
nums2= np.random.randint(1, 101, (5, 5))
print(nums2)
print(nums2.max())
print(nums2.max()/2 + 7) # No, its 57.

[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]
100
57.0
