In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy

In [3]:
data = {'hours_of_calling_customers': [2, 3, 4, 5, 6, 1.5, 5, 7, 8, 10], 'money_earned':[50, 70, 90, 100, 110, 40, 110, 130, 145, 180]}
df = pd.DataFrame(data)
df

hours_of_calling_customers  money_earned
0                         2.0            50
1                         3.0            70
2                         4.0            90
3                         5.0           100
4                         6.0           110
5                         1.5            40
6                         5.0           110
7                         7.0           130
8                         8.0           145
9                        10.0           180

In [13]:
X = df.drop('money_earned', axis= 1)
y = df['money_earned']

train_rmse_errors = []
test_rmse_errors= []

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import *

polynomial_converter = PolynomialFeatures(degree=3, include_bias = False)
polynomial_features = polynomial_converter.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(polynomial_features, y, test_size = 0.3, random_state = 42)
X_train

array([[   2.,    4.,    8.],
       [   7.,   49.,  343.],
       [   4.,   16.,   64.],
       [  10.,  100., 1000.],
       [   6.,   36.,  216.],
       [   5.,   25.,  125.],
       [   5.,   25.,  125.]])

In [11]:
scaler = StandardScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train

array([[-1.53864364, -1.11419179, -0.8278501 ],
       [ 0.61545745,  0.43193338,  0.23588058],
       [-0.6770032 , -0.70189174, -0.65003243],
       [ 1.90791811,  2.18420857,  2.32206282],
       [ 0.18463724, -0.014725  , -0.16738449],
       [-0.24618298, -0.39266671, -0.45633819],
       [-0.24618298, -0.39266671, -0.45633819]])

In [63]:
lasso_cv2 = LassoCV(eps=0.1, alphas=200)
lasso_cv2.fit(scaled_X_train, y_train)

test_predictions2 = lasso_cv2.predict(scaled_X_test)
print(test_predictions2)
train_predictions2  = lasso_cv2.predict(scaled_X_train)
print(train_predictions2)

[144.19318182  73.79545455  52.67613636]
[ 59.71590909 130.11363636  87.875      172.35227273 116.03409091
 101.95454545 101.95454545]


In [83]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
train_mae = mean_absolute_error(y_train, train_predictions2)
train_rmse = np.sqrt(mean_squared_error(y_train, train_predictions2))

test_mae = mean_absolute_error(y_test, test_predictions2)
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions2))


print(f"Train MAE: {train_mae:}, Train RMSE: {train_rmse:}")
print(f"Test MAE:  {test_mae:}, Test RMSE:  {test_rmse:}")

Train MAE: 5.090909090909094, Train RMSE: 6.122266153732856
Test MAE:  5.759469696969703, Test RMSE:  7.653776059232209


In [71]:
lasso_cv1 = LassoCV(eps=0.3, alphas=100)
lasso_cv1.fit(scaled_X_train, y_train)

test_predictions1 = lasso_cv1.predict(scaled_X_test)
print(test_predictions1)
train_predictions1 = lasso_cv1.predict(scaled_X_train)
print(train_predictions1)

[136.59469697  81.84090909  65.41477273]
[ 70.89015152 125.64393939  92.79166667 158.49621212 114.69318182
 103.74242424 103.74242424]


In [85]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
train_mae = mean_absolute_error(y_train, train_predictions1)
train_rmse = np.sqrt(mean_squared_error(y_train, train_predictions1))

test_mae = mean_absolute_error(y_test, test_predictions1)
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions1))


print(f"Train MAE: {train_mae:}, Train RMSE: {train_rmse:}")
print(f"Test MAE:  {test_mae:}, Test RMSE:  {test_rmse:}")

Train MAE: 9.176406926406928, Train RMSE: 11.956880502120585
Test MAE:  15.220328282828286, Test RMSE:  16.89937789692588


In [77]:
print(f"200alpha coef:{lasso_cv2.coef_}")
print(f"100alpha coef:{lasso_cv1.coef_}")

200alpha coef:[32.68079086  0.          0.        ]
100alpha coef:[25.41839289  0.          0.        ]


In [81]:
print(f"200alpha best alpha: {lasso_cv2.alpha_}")
print(f"100alpha best alpha: {lasso_cv1.alpha_}")

200alpha best alpha: 3.6311989838903154
100alpha best alpha: 10.893596951670945


In [ ]:
# Model 2 is better because the rmse is 7.65 compared to 16.9