In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy

In [4]:
data = {'hours_of_calling_customers': [2, 3, 4, 5, 6, 1.5, 5, 7, 8, 10], 'money_earned':[50, 70, 90, 100, 110, 40, 110, 130, 145, 180]}
df = pd.DataFrame(data)
df

hours_of_calling_customers  money_earned
0                         2.0            50
1                         3.0            70
2                         4.0            90
3                         5.0           100
4                         6.0           110
5                         1.5            40
6                         5.0           110
7                         7.0           130
8                         8.0           145
9                        10.0           180

In [8]:
X = df.drop('money_earned', axis= 1)
y = df['money_earned']

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import *

polynomial_converter = PolynomialFeatures(degree=3, include_bias = False)
polynomial_features = polynomial_converter.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(polynomial_features, y, test_size = 0.3, random_state = 42)
X_train

array([[   2.,    4.,    8.],
       [   7.,   49.,  343.],
       [   4.,   16.,   64.],
       [  10.,  100., 1000.],
       [   6.,   36.,  216.],
       [   5.,   25.,  125.],
       [   5.,   25.,  125.]])

In [10]:
scaler = StandardScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train

array([[-1.53864364, -1.11419179, -0.8278501 ],
       [ 0.61545745,  0.43193338,  0.23588058],
       [-0.6770032 , -0.70189174, -0.65003243],
       [ 1.90791811,  2.18420857,  2.32206282],
       [ 0.18463724, -0.014725  , -0.16738449],
       [-0.24618298, -0.39266671, -0.45633819],
       [-0.24618298, -0.39266671, -0.45633819]])

In [63]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error

ridge_model = Ridge(alpha= 5)
ridge_model.fit(scaled_X_train, y_train)
test_predictions = ridge_model.predict(scaled_X_test)



[144.19318182  73.79545455  52.67613636]
[ 59.71590909 130.11363636  87.875      172.35227273 116.03409091
 101.95454545 101.95454545]


In [16]:
from sklearn.model_selection import cross_val_score

for alpha in [10, 100]:
    ridge = Ridge(alpha= alpha)
    mae_scores = cross_val_score(ridge, scaled_X_train, y_train, scoring='neg_mean_absolute_error', cv=5)
    mean_mae = -mae_scores.mean()
    print(f"Alpha={alpha} - Mean MAE: {mean_mae:.2f}")

# alpha 10 performed better

Alpha=10 - Mean MAE: 12.71
Alpha=100 - Mean MAE: 18.17


In [20]:
from sklearn.model_selection import cross_validate

for alpha in [1, 10, 100]:
    ridge = Ridge(alpha= alpha)
    scores = cross_validate(ridge, scaled_X_train, y_train, cv=5, scoring={'MAE': 'neg_mean_absolute_error', 'MSE': 'neg_mean_squared_error'})
    mean_mae =- scores['test_MAE'].mean()
    mean_mse =- scores['test_MSE'].mean()
    print(f"Alpha={alpha} -> Mean MAE: {mean_mae:.2f}, Mean MSE: {mean_mse:.2f}")
# alpha 1 performed best

Alpha=1 -> Mean MAE: 7.87, Mean MSE: 138.76
Alpha=10 -> Mean MAE: 12.71, Mean MSE: 443.70
Alpha=100 -> Mean MAE: 18.17, Mean MSE: 1000.07
