In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import scipy

In [4]:
data = {'hours_of_calling_customers': [2, 3, 4, 5, 6, 1.5, 5, 7, 8, 10], 'money_earned':[50, 70, 90, 100, 110, 40, 110, 130, 145, 180]}
df = pd.DataFrame(data)
df

hours_of_calling_customers  money_earned
0                         2.0            50
1                         3.0            70
2                         4.0            90
3                         5.0           100
4                         6.0           110
5                         1.5            40
6                         5.0           110
7                         7.0           130
8                         8.0           145
9                        10.0           180

In [24]:
X = df.drop('money_earned', axis= 1)
y = df['money_earned']

from sklearn.linear_model import LinearRegression
final_model = LinearRegression()
final_model.fit(X_train, y_train)
final_model.coef_


array([15.90403338])

In [32]:
from joblib import dump, load
dump(final_model, 'final_money_earned.joblib')

['final_money_earned.joblib']

In [34]:
loaded_model = load('final_money_earned.joblib')
loaded_model.coef_

array([15.90403338])

In [48]:
loaded_model.predict([[5.5]])

C:\Users\PC\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([108.44228095])

In [50]:
loaded_model.predict([[15]])

C:\Users\PC\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([259.53059805])